### ISSUE TITLE
Kernel not booting bootloop

### ISSUE THREAD

**Issue by muralivijay** [zoggn/kernel_lenovo_a2010#1]
Why when try load a custom kernel is not booting my lenovo a2010-a device ?  even tried official kernel source code from lenovo 3.10.65 . also tried yours kernel source 3.18.19 to same here .bootloops at lenovo logo . here my last kmsg

ram console header, hw_status: 0, fiq step 0.
header may be corrupted, dump the raw buffer for reference only

But that 3.18.19 ( queen) build kernel boots perfectly . also stock based queen 3.10.65 boots well.

* bootloader is locked

**Comment by zoggn** [comment]
![image](https://user-images.githubusercontent.com/20438767/103413598-f9942780-4b82-11eb-8b1c-b6f63bdad7f0.png)

**Comment by muralivijay** [comment]
@zoggn can you please share rom download link please

**Comment by zoggn** [comment]
https://4pda.ru/forum/index.php?showtopic=798894&view=findpost&p=88112659

**Comment by muralivijay** [comment]
@zoggn already gotcha thanks . but why are using custom firmware ? instead of stock one for oreo for ex preloader? where you get this firmwares ?

**Comment by zoggn** [comment]
I`m using stock preloader and lk with stock etc/firmware.

**Comment by muralivijay** [comment]
> I`m using stock preloader and lk with stock etc/firmware.

what about other firmwares ? secro.img , trustzone etc?
